name: "runs a script"

on:
    push:
        branches:
            - master
            - main

jobs:
    run-script:
        runs-on: ubuntu-latest
        
    steps:
       -  name: checkout code
         uses: actions/checkout@v4

       -  name: Run hello.sh
          run:  bash hello.sh