name: "my practice in ci cd pipeline"

on:
    push:

        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest


        
        steps:
          - name: say hello
          
            runs: echo " the github action is working"
